name = "heart-of-crown-randomizer"
pages_build_output_dir = "packages/site/.svelte-kit/cloudflare"
compatibility_date = "2026-04-05"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[vars]
NODE_VERSION = "24.12.0"
