import { BasicCard } from "../type";

export const basics = [
  {
    id: 6,
    type: "basic",
    name: "農村",
    mainType: ["territory"],
    cost: 1,
    succession: -2,
    coin: 1,
    link: 1,
    effect: "",
    edition: 0,
  },
  {
    id: 7,
    type: "basic",
    name: "果樹園",
    mainType: ["territory"],
    cost: 2,
    coin: 1,
    link: 1,
    effect: "このカードは「農村」としても扱う。",
    edition: 0,
  },
  {
    id: 8,
    type: "basic",
    name: "都市",
    mainType: ["territory"],
    cost: 3,
    coin: 2,
    link: 1,
    effect: "",
    edition: 0,
  },
  {
    id: 9,
    type: "basic",
    name: "大都市",
    mainType: ["territory"],
    cost: 6,
    coin: 3,
    link: 1,
    effect: "",
    edition: 0,
  },
  {
    id: 10,
    type: "basic",
    name: "見習い侍女",
    mainType: ["succession"],
    subType: "maid",
    cost: 2,
    succession: -2,
    link: 0,
    effect: "",
    edition: 0,
  },
  {
    id: 11,
    type: "basic",
    name: "宮廷侍女",
    mainType: ["succession"],
    subType: "maid",
    cost: 3,
    succession: 2,
    link: 0,
    effect: "",
    edition: 0,
  },
  {
    id: 12,
    type: "basic",
    name: "議員",
    mainType: ["succession"],
    cost: 5,
    succession: 3,
    link: 0,
    effect: "",
    edition: 0,
  },
  {
    id: 13,
    type: "basic",
    name: "公爵",
    mainType: ["succession"],
    cost: 8,
    succession: 6,
    link: 0,
    effect: "",
    edition: 0,
  },
  {
    id: 14,
    type: "basic",
    name: "呪い",
    mainType: ["disaster"],
    cost: 0,
    link: 0,
    effect: "",
    edition: 0,
  },
] as const satisfies BasicCard[];
